/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as CandidatesIndexRouteImport } from './routes/candidates/index'
import { Route as CandidatesIdRouteImport } from './routes/candidates/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/recruiter': typeof RecruiterRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/recruiter': typeof RecruiterRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates': typeof CandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/recruiter': typeof RecruiterRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ingest' | '/recruiter' | '/candidates/$id' | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ingest' | '/recruiter' | '/candidates/$id' | '/candidates'
  id:
    | '__root__'
    | '/'
    | '/ingest'
    | '/recruiter'
    | '/candidates/$id'
    | '/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngestRoute: typeof IngestRoute
  RecruiterRoute: typeof RecruiterRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngestRoute: IngestRoute,
  RecruiterRoute: RecruiterRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
